<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Flight Confirmation – {{ $segment->flight_number }}</title>
<style>
@page{margin:20mm 15mm}
body{font-family:'DejaVu Sans',sans-serif;font-size:10pt;color:#333;line-height:1.5}
.header{text-align:center;border-bottom:3px solid #1a56db;padding-bottom:10px;margin-bottom:20px}
.header h1{color:#1a56db;font-size:18pt;margin:0}
.header p{margin:2px 0;font-size:9pt;color:#6b7280}
.section{margin-bottom:18px;page-break-inside:avoid}
.section h3{font-size:10pt;color:#1a56db;text-transform:uppercase;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin:0 0 8px}
table{width:100%;border-collapse:collapse;font-size:9pt}
table th{background:#f3f4f6;text-align:left;padding:5px 6px;font-weight:600;border:1px solid #d1d5db}
table td{padding:4px 6px;border:1px solid #d1d5db;vertical-align:top}
.grid-2{display:flex;gap:15px}
.grid-2>div{flex:1}
.label{color:#6b7280;font-size:8pt;text-transform:uppercase;margin-bottom:1px}
.value{font-weight:600;font-size:10pt}
.footer{text-align:center;border-top:2px solid #e5e7eb;padding-top:10px;margin-top:20px;font-size:8pt;color:#9ca3af}
.flight-route{display:flex;align-items:center;justify-content:center;gap:15px;margin:10px 0}
.flight-route .airport{text-align:center}
.flight-route .airport .code{font-size:16pt;font-weight:700;color:#1a56db}
.flight-route .airport .city{font-size:8pt;color:#6b7280}
.flight-route .arrow{font-size:18pt;color:#9ca3af}
</style>
</head>
<body>

<div class="header">
    <h1>TravelBox</h1>
    <p style="font-size:11pt;font-weight:600">Flight Booking Confirmation</p>
    <p>{{ $segment->airline }} {{ $segment->flight_number }} &bull; {{ $trip->trip_number }}</p>
</div>

<div class="flight-route">
    <div class="airport">
        <div class="code">{{ $segment->departure_airport }}</div>
        <div class="city">{{ $segment->departure_datetime?->format('M d, H:i') }}</div>
    </div>
    <div class="arrow">→</div>
    <div class="airport">
        <div class="code">{{ $segment->arrival_airport }}</div>
        <div class="city">{{ $segment->arrival_datetime?->format('M d, H:i') }}</div>
    </div>
</div>

<div class="section">
    <table>
        <tr>
            <td style="width:25%"><div class="label">Airline</div><div class="value">{{ $segment->airline }}</div></td>
            <td style="width:25%"><div class="label">Flight Number</div><div class="value">{{ $segment->flight_number }}</div></td>
            <td style="width:25%"><div class="label">Travel Class</div><div class="value">{{ $segment->travel_class ?? '—' }}</div></td>
            <td style="width:25%"><div class="label">Status</div><div class="value">{{ ucfirst($segment->status ?? 'confirmed') }}</div></td>
        </tr>
    </table>
</div>

<div class="section">
    <div class="grid-2">
        <div>
            <div class="label">Booking Reference</div>
            <div class="value">{{ $segment->booking_reference ?: '—' }}</div>
            @if ($segment->ticket_number)<div style="font-size:9pt;color:#6b7280">Ticket: {{ $segment->ticket_number }}</div>@endif
        </div>
        <div>
            <div class="label">Departure / Arrival</div>
            <div class="value">{{ $segment->departure_datetime?->format('M d, Y H:i') }}</div>
            <div style="font-size:9pt;color:#6b7280">{{ $segment->arrival_datetime?->format('M d, Y H:i') }}</div>
        </div>
    </div>
</div>

@if ($trip->passengers->isNotEmpty())
<div class="section">
    <h3>Passengers</h3>
    <table>
        <thead><tr><th>#</th><th>Name</th></tr></thead>
        <tbody>
        @foreach ($trip->passengers as $i => $p)
        <tr><td>{{ $i + 1 }}</td><td>{{ $p->first_name }} {{ $p->last_name }}</td></tr>
        @endforeach
        </tbody>
    </table>
</div>
@endif

@if ($segment->relationLoaded('supplier') && $segment->supplier)
<div class="section">
    <h3>Supplier Information</h3>
    <table>
        <tr>
            <td style="width:50%"><div class="label">Supplier</div><div class="value">{{ $segment->supplier->name ?? '—' }}</div></td>
            <td style="width:50%"><div class="label">Contact</div><div class="value">{{ $segment->supplier->contact_person ?? '—' }}</div></td>
        </tr>
        <tr>
            <td><div class="label">Email</div><div style="font-size:9pt">{{ $segment->supplier->email ?? '—' }}</div></td>
            <td><div class="label">Phone</div><div style="font-size:9pt">{{ $segment->supplier->phone ?? '—' }}</div></td>
        </tr>
    </table>
</div>
@endif

<div class="footer">
    <p>Generated by TravelBox ERP &bull; {{ now()->format('M d, Y H:i') }} &bull; travelbox.my</p>
    <p style="font-size:7pt">This is a computer-generated confirmation. Please verify all flight details with the airline.</p>
</div>

</body>
</html>
