<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Hotel Voucher – {{ $booking->hotel_name }}</title>
<style>
@page{margin:20mm 15mm}
body{font-family:'DejaVu Sans',sans-serif;font-size:10pt;color:#333;line-height:1.5}
.header{text-align:center;border-bottom:3px solid #1a56db;padding-bottom:10px;margin-bottom:20px}
.header h1{color:#1a56db;font-size:18pt;margin:0}
.header p{margin:2px 0;font-size:9pt;color:#6b7280}
.section{margin-bottom:18px;page-break-inside:avoid}
.section h3{font-size:10pt;color:#1a56db;text-transform:uppercase;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin:0 0 8px}
table{width:100%;border-collapse:collapse;font-size:9pt}
table th{background:#f3f4f6;text-align:left;padding:5px 6px;font-weight:600;border:1px solid #d1d5db}
table td{padding:4px 6px;border:1px solid #d1d5db;vertical-align:top}
.grid-2{display:flex;gap:15px}
.grid-2>div{flex:1}
.label{color:#6b7280;font-size:8pt;text-transform:uppercase;margin-bottom:1px}
.value{font-weight:600;font-size:10pt}
.footer{text-align:center;border-top:2px solid #e5e7eb;padding-top:10px;margin-top:20px;font-size:8pt;color:#9ca3af}
.hotel-name{font-size:16pt;font-weight:700;color:#1a56db;margin:0 0 5px}
.hotel-address{font-size:9pt;color:#6b7280;margin:0 0 15px}
</style>
</head>
<body>

<div class="header">
    <h1>TravelBox</h1>
    <p style="font-size:11pt;font-weight:600">Hotel Voucher</p>
    <p>{{ $trip->trip_number }} &bull; {{ $booking->hotel_name }}</p>
</div>

<p class="hotel-name">{{ $booking->hotel_name }}</p>
@if ($booking->address)<p class="hotel-address">{{ $booking->address }}</p>@endif

<div class="section">
    <div class="grid-2">
        <div>
            <div class="label">Check-in</div>
            <div class="value">{{ $booking->check_in?->format('M d, Y') }}</div>
            @if ($booking->check_in_time)<div style="font-size:9pt;color:#6b7280">{{ $booking->check_in_time }}</div>@endif
        </div>
        <div>
            <div class="label">Check-out</div>
            <div class="value">{{ $booking->check_out?->format('M d, Y') }}</div>
            @if ($booking->check_out_time)<div style="font-size:9pt;color:#6b7280">{{ $booking->check_out_time }}</div>@endif
        </div>
    </div>
</div>

<div class="section">
    <table>
        <tr>
            <td style="width:33%"><div class="label">Room Type</div><div class="value">{{ $booking->room_type ?? '—' }}</div></td>
            <td style="width:33%"><div class="label">Meal Plan</div><div class="value">{{ $booking->meal_plan ?? '—' }}</div></td>
            <td style="width:33%"><div class="label">Rooms</div><div class="value">{{ $booking->number_of_rooms ?? 1 }}</div></td>
        </tr>
    </table>
</div>

<div class="section">
    <div class="grid-2">
        <div>
            <div class="label">Booking Reference</div>
            <div class="value">{{ $booking->booking_reference ?: '—' }}</div>
            @if ($booking->confirmation_number)<div style="font-size:9pt;color:#6b7280">Confirmation: {{ $booking->confirmation_number }}</div>@endif
        </div>
        <div>
            <div class="label">City</div>
            <div class="value">{{ $booking->city ?? '—' }}</div>
        </div>
    </div>
</div>

@if ($trip->passengers->isNotEmpty())
<div class="section">
    <h3>Guests</h3>
    <table>
        <thead><tr><th>#</th><th>Name</th></tr></thead>
        <tbody>
        @foreach ($trip->passengers as $i => $p)
        <tr><td>{{ $i + 1 }}</td><td>{{ $p->first_name }} {{ $p->last_name }}</td></tr>
        @endforeach
        </tbody>
    </table>
</div>
@endif

@if ($booking->relationLoaded('supplier') && $booking->supplier)
<div class="section">
    <h3>Supplier Information</h3>
    <table>
        <tr>
            <td style="width:50%"><div class="label">Supplier</div><div class="value">{{ $booking->supplier->name ?? '—' }}</div></td>
            <td style="width:50%"><div class="label">Contact</div><div class="value">{{ $booking->supplier->contact_person ?? '—' }}</div></td>
        </tr>
        <tr>
            <td><div class="label">Email</div><div style="font-size:9pt">{{ $booking->supplier->email ?? '—' }}</div></td>
            <td><div class="label">Phone</div><div style="font-size:9pt">{{ $booking->supplier->phone ?? '—' }}</div></td>
        </tr>
    </table>
</div>
@endif

@if ($booking->notes)
<div class="section">
    <h3>Notes</h3>
    <p style="font-size:9pt">{{ $booking->notes }}</p>
</div>
@endif

<div class="footer">
    <p>Generated by TravelBox ERP &bull; {{ now()->format('M d, Y H:i') }} &bull; travelbox.my</p>
    <p style="font-size:7pt">This is a computer-generated voucher. Please present to the hotel upon check-in.</p>
</div>

</body>
</html>
