<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Insurance Certificate – {{ $policy->policy_number }}</title>
<style>
@page{margin:20mm 15mm}
body{font-family:'DejaVu Sans',sans-serif;font-size:10pt;color:#333;line-height:1.5}
.header{text-align:center;border-bottom:3px solid #1a56db;padding-bottom:10px;margin-bottom:20px}
.header h1{color:#1a56db;font-size:18pt;margin:0}
.header p{margin:2px 0;font-size:9pt;color:#6b7280}
.section{margin-bottom:18px;page-break-inside:avoid}
.section h3{font-size:10pt;color:#1a56db;text-transform:uppercase;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin:0 0 8px}
table{width:100%;border-collapse:collapse;font-size:9pt}
table th{background:#f3f4f6;text-align:left;padding:5px 6px;font-weight:600;border:1px solid #d1d5db}
table td{padding:4px 6px;border:1px solid #d1d5db;vertical-align:top}
.grid-2{display:flex;gap:15px}
.grid-2>div{flex:1}
.label{color:#6b7280;font-size:8pt;text-transform:uppercase;margin-bottom:1px}
.value{font-weight:600;font-size:10pt}
.footer{text-align:center;border-top:2px solid #e5e7eb;padding-top:10px;margin-top:20px;font-size:8pt;color:#9ca3af}
.policy-number{font-size:16pt;font-weight:700;color:#1a56db;margin:0 0 5px;text-align:center}
.coverage-block{background:#f9fafb;border:1px solid #e5e7eb;border-radius:4px;padding:10px;margin-bottom:10px}
.coverage-block p{margin:2px 0;font-size:9pt}
</style>
</head>
<body>

<div class="header">
    <h1>TravelBox</h1>
    <p style="font-size:11pt;font-weight:600">Insurance Certificate</p>
    <p>{{ $trip->trip_number }} &bull; {{ $policy->type ?? 'travel' }}</p>
</div>

<p class="policy-number">{{ $policy->policy_number ?? '—' }}</p>

<div class="section">
    <div class="grid-2">
        <div>
            <div class="label">Policy Type</div>
            <div class="value">{{ str_replace('_', ' ', ucfirst($policy->type ?? 'travel')) }}</div>
        </div>
        <div>
            <div class="label">Status</div>
            <div class="value">{{ ucfirst($policy->status ?? 'active') }}</div>
        </div>
    </div>
</div>

<div class="section">
    <table>
        <tr>
            <td style="width:33%"><div class="label">Valid From</div><div class="value">{{ $policy->start_date?->format('M d, Y') ?: '—' }}</div></td>
            <td style="width:33%"><div class="label">Valid To</div><div class="value">{{ $policy->end_date?->format('M d, Y') ?: '—' }}</div></td>
            <td style="width:33%"><div class="label">Provider</div><div class="value">{{ $policy->provider ?? '—' }}</div></td>
        </tr>
    </table>
</div>

@if ($policy->coverage_details)
<div class="section">
    <h3>Coverage Details</h3>
    <div class="coverage-block">
        {!! nl2br(e($policy->coverage_details)) !!}
    </div>
</div>
@endif

@if ($trip->passengers->isNotEmpty())
<div class="section">
    <h3>Insured Persons</h3>
    <table>
        <thead><tr><th>#</th><th>Name</th></tr></thead>
        <tbody>
        @foreach ($trip->passengers as $i => $p)
        <tr><td>{{ $i + 1 }}</td><td>{{ $p->first_name }} {{ $p->last_name }}</td></tr>
        @endforeach
        </tbody>
    </table>
</div>
@endif

@if ($policy->notes)
<div class="section">
    <h3>Notes</h3>
    <p style="font-size:9pt">{{ $policy->notes }}</p>
</div>
@endif

<div class="footer">
    <p>Generated by TravelBox ERP &bull; {{ now()->format('M d, Y H:i') }} &bull; travelbox.my</p>
    <p style="font-size:7pt">This is a computer-generated certificate. Please carry this document during your trip.</p>
</div>

</body>
</html>
