<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Receipt – {{ $payment->receipt_number ?? $payment->id }}</title>
<style>
@page{margin:20mm 15mm}
body{font-family:'DejaVu Sans',sans-serif;font-size:10pt;color:#333;line-height:1.5}
.header{text-align:center;border-bottom:3px solid #1a56db;padding-bottom:10px;margin-bottom:20px}
.header h1{color:#1a56db;font-size:18pt;margin:0}
.header p{margin:2px 0;font-size:9pt;color:#6b7280}
.section{margin-bottom:18px;page-break-inside:avoid}
.section h3{font-size:10pt;color:#1a56db;text-transform:uppercase;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin:0 0 8px}
table{width:100%;border-collapse:collapse;font-size:9pt}
table th{background:#f3f4f6;text-align:left;padding:5px 6px;font-weight:600;border:1px solid #d1d5db}
table td{padding:4px 6px;border:1px solid #d1d5db;vertical-align:top}
.grid-2{display:flex;gap:15px}
.grid-2>div{flex:1}
.label{color:#6b7280;font-size:8pt;text-transform:uppercase;margin-bottom:1px}
.value{font-weight:600;font-size:10pt}
.footer{text-align:center;border-top:2px solid #e5e7eb;padding-top:10px;margin-top:20px;font-size:8pt;color:#9ca3af}
.receipt-amount{font-size:24pt;color:#1a56db;font-weight:700;margin:0}
.receipt-status{display:inline-block;padding:2px 8px;border-radius:3px;font-size:8pt;font-weight:600;text-transform:uppercase}
.receipt-status-completed{background:#d1fae5;color:#065f46}
.receipt-status-pending{background:#fef3c7;color:#92400e}
.receipt-status-failed{background:#fee2e2;color:#991b1b}
</style>
</head>
<body>

<div class="header">
    <h1>TravelBox</h1>
    <p style="font-size:11pt;font-weight:600">PAYMENT RECEIPT</p>
    <p>{{ $payment->receipt_number ?? 'RECEIPT-'.$payment->id }} &bull; <span class="receipt-status receipt-status-{{ $payment->status }}">{{ $payment->status }}</span></p>
</div>

<div style="text-align:center;margin-bottom:20px">
    <p class="receipt-amount">{{ number_format($payment->amount, 2) }}</p>
    <p style="font-size:9pt;color:#6b7280;margin:0">{{ $payment->currency ?? 'MYR' }}</p>
</div>

<div class="section">
    <div class="grid-2">
        <div>
            <div class="label">Payer</div>
            <div class="value">{{ $payment->payer?->full_name ?? '—' }}</div>
            @if ($payment->payer?->email)<div style="font-size:9pt;color:#6b7280">{{ $payment->payer->email }}</div>@endif
            @if ($payment->payer?->phone)<div style="font-size:9pt;color:#6b7280">{{ $payment->payer->phone }}</div>@endif
        </div>
        <div>
            <div class="label">Payment Info</div>
            <div style="font-size:9pt;color:#6b7280">
                Date: {{ $payment->payment_date?->format('M d, Y') }}<br>
                Method: {{ str_replace('_', ' ', ucfirst($payment->payment_method ?? '—')) }}<br>
                Reference: {{ $payment->reference ?? '—' }}<br>
                @if ($payment->trip)Trip: {{ $payment->trip->trip_number }}@endif
            </div>
        </div>
    </div>
</div>

@if ($payment->description)
<div class="section">
    <h3>Description</h3>
    <p style="font-size:9pt">{{ $payment->description }}</p>
</div>
@endif

<div class="footer">
    <p>Generated by TravelBox ERP &bull; {{ now()->format('M d, Y H:i') }} &bull; travelbox.my</p>
    <p style="font-size:7pt">This is a computer-generated receipt. Please retain for your records.</p>
</div>

</body>
</html>
