<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Train Voucher – {{ $booking->train_company ?? 'Train' }}</title>
<style>
@page{margin:20mm 15mm}
body{font-family:'DejaVu Sans',sans-serif;font-size:10pt;color:#333;line-height:1.5}
.header{text-align:center;border-bottom:3px solid #57534e;padding-bottom:10px;margin-bottom:20px}
.header h1{color:#57534e;font-size:18pt;margin:0}
.header p{margin:2px 0;font-size:9pt;color:#6b7280}
.section{margin-bottom:18px;page-break-inside:avoid}
.section h3{font-size:10pt;color:#57534e;text-transform:uppercase;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin:0 0 8px}
table{width:100%;border-collapse:collapse;font-size:9pt}
table th{background:#f3f4f6;text-align:left;padding:5px 6px;font-weight:600;border:1px solid #d1d5db}
table td{padding:4px 6px;border:1px solid #d1d5db;vertical-align:top}
.grid-2{display:flex;gap:15px}
.grid-2>div{flex:1}
.label{color:#6b7280;font-size:8pt;text-transform:uppercase;margin-bottom:1px}
.value{font-weight:600;font-size:10pt}
.footer{text-align:center;border-top:2px solid #e5e7eb;padding-top:10px;margin-top:20px;font-size:8pt;color:#9ca3af}
</style>
</head>
<body>

<div class="header">
    <h1>TravelBox</h1>
    <p style="font-size:11pt;font-weight:600">Train Voucher</p>
    <p>{{ $trip->trip_number }} &bull; {{ $booking->train_company ?? 'Train' }}</p>
</div>

<div class="section">
    <table>
        <tr>
            <td style="width:50%"><div class="label">Train Company</div><div class="value">{{ $booking->train_company ?: '—' }}</div></td>
            <td style="width:50%"><div class="label">Train Number</div><div class="value">{{ $booking->train_number ?: '—' }}</div></td>
        </tr>
    </table>
</div>

<div class="section">
    <table>
        <tr>
            <td style="width:40%"><div class="label">Departure Station</div><div class="value">{{ $booking->departure_station ?: '—' }}</div></td>
            <td style="width:20%"><div class="label">Departure</div><div class="value" style="font-size:9pt">{{ $booking->departure_datetime?->format('M d, H:i') }}</div></td>
            <td style="width:40%"><div class="label">Arrival Station</div><div class="value">{{ $booking->arrival_station ?: '—' }}</div></td>
        </tr>
    </table>
</div>

<div class="section">
    <table>
        <tr>
            <td style="width:50%"><div class="label">Class</div><div class="value">{{ $booking->class ?: '—' }}</div></td>
            <td style="50%"><div class="label">Ticket Reference</div><div class="value">{{ $booking->ticket_reference ?: '—' }}</div></td>
        </tr>
    </table>
</div>

@if ($trip->passengers->isNotEmpty())
<div class="section">
    <h3>Passengers</h3>
    <table>
        <thead><tr><th>#</th><th>Name</th></tr></thead>
        <tbody>
        @foreach ($trip->passengers as $i => $p)
        <tr><td>{{ $i + 1 }}</td><td>{{ $p->first_name }} {{ $p->last_name }}</td></tr>
        @endforeach
        </tbody>
    </table>
</div>
@endif

<div class="footer">
    <p>Generated by TravelBox ERP &bull; {{ now()->format('M d, Y H:i') }} &bull; travelbox.my</p>
</div>

</body>
</html>
