<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Transfer Voucher – {{ $booking->type ?? 'Transfer' }} {{ $booking->id }}</title>
<style>
@page{margin:20mm 15mm}
body{font-family:'DejaVu Sans',sans-serif;font-size:10pt;color:#333;line-height:1.5}
.header{text-align:center;border-bottom:3px solid #1a56db;padding-bottom:10px;margin-bottom:20px}
.header h1{color:#1a56db;font-size:18pt;margin:0}
.header p{margin:2px 0;font-size:9pt;color:#6b7280}
.section{margin-bottom:18px;page-break-inside:avoid}
.section h3{font-size:10pt;color:#1a56db;text-transform:uppercase;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin:0 0 8px}
table{width:100%;border-collapse:collapse;font-size:9pt}
table th{background:#f3f4f6;text-align:left;padding:5px 6px;font-weight:600;border:1px solid #d1d5db}
table td{padding:4px 6px;border:1px solid #d1d5db;vertical-align:top}
.grid-2{display:flex;gap:15px}
.grid-2>div{flex:1}
.label{color:#6b7280;font-size:8pt;text-transform:uppercase;margin-bottom:1px}
.value{font-weight:600;font-size:10pt}
.footer{text-align:center;border-top:2px solid #e5e7eb;padding-top:10px;margin-top:20px;font-size:8pt;color:#9ca3af}
.transfer-type{display:inline-block;padding:3px 10px;border-radius:4px;font-size:9pt;font-weight:700;text-transform:uppercase}
.transfer-type-arrival{background:#dbeafe;color:#1e40af}
.transfer-type-departure{background:#fef3c7;color:#92400e}
</style>
</head>
<body>

<div class="header">
    <h1>TravelBox</h1>
    <p style="font-size:11pt;font-weight:600">Transfer Voucher</p>
    <p>{{ $trip->trip_number }} &bull; <span class="transfer-type transfer-type-{{ $booking->type ?? 'transfer' }}">{{ $booking->type ?? 'Transfer' }}</span></p>
</div>

<div class="section">
    <table>
        <tr>
            <td style="width:50%">
                <div class="label">Pickup Location</div>
                <div class="value">{{ $booking->pickup_location ?? '—' }}</div>
            </td>
            <td style="width:50%">
                <div class="label">Dropoff Location</div>
                <div class="value">{{ $booking->dropoff_location ?? '—' }}</div>
            </td>
        </tr>
    </table>
</div>

<div class="section">
    <div class="grid-2">
        <div>
            <div class="label">Pickup Date &amp; Time</div>
            <div class="value">{{ $booking->pickup_datetime?->format('M d, Y H:i') }}</div>
        </div>
        <div>
            <div class="label">Vehicle Type</div>
            <div class="value">{{ $booking->vehicle_type ?? '—' }}</div>
        </div>
    </div>
</div>

<div class="section">
    <table>
        <tr>
            <td style="width:50%"><div class="label">Passenger Count</div><div class="value">{{ $booking->passenger_count ?? '—' }}</div></td>
            <td style="width:50%"><div class="label">Booking Reference</div><div class="value">{{ $booking->booking_reference ?: '—' }}</div></td>
        </tr>
        @if ($booking->driver_name || $booking->driver_phone)
        <tr>
            <td><div class="label">Driver Name</div><div style="font-size:9pt">{{ $booking->driver_name ?? '—' }}</div></td>
            <td><div class="label">Driver Phone</div><div style="font-size:9pt">{{ $booking->driver_phone ?? '—' }}</div></td>
        </tr>
        @endif
    </table>
</div>

@if ($trip->passengers->isNotEmpty())
<div class="section">
    <h3>Passengers</h3>
    <table>
        <thead><tr><th>#</th><th>Name</th></tr></thead>
        <tbody>
        @foreach ($trip->passengers as $i => $p)
        <tr><td>{{ $i + 1 }}</td><td>{{ $p->first_name }} {{ $p->last_name }}</td></tr>
        @endforeach
        </tbody>
    </table>
</div>
@endif

@if ($booking->notes)
<div class="section">
    <h3>Notes</h3>
    <p style="font-size:9pt">{{ $booking->notes }}</p>
</div>
@endif

<div class="footer">
    <p>Generated by TravelBox ERP &bull; {{ now()->format('M d, Y H:i') }} &bull; travelbox.my</p>
    <p style="font-size:7pt">This is a computer-generated voucher. Please present to the driver upon pickup.</p>
</div>

</body>
</html>
