<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Visa Confirmation – {{ $visa->country }}</title>
<style>
@page{margin:20mm 15mm}
body{font-family:'DejaVu Sans',sans-serif;font-size:10pt;color:#333;line-height:1.5}
.header{text-align:center;border-bottom:3px solid #1a56db;padding-bottom:10px;margin-bottom:20px}
.header h1{color:#1a56db;font-size:18pt;margin:0}
.header p{margin:2px 0;font-size:9pt;color:#6b7280}
.section{margin-bottom:18px;page-break-inside:avoid}
.section h3{font-size:10pt;color:#1a56db;text-transform:uppercase;border-bottom:1px solid #e5e7eb;padding-bottom:4px;margin:0 0 8px}
table{width:100%;border-collapse:collapse;font-size:9pt}
table th{background:#f3f4f6;text-align:left;padding:5px 6px;font-weight:600;border:1px solid #d1d5db}
table td{padding:4px 6px;border:1px solid #d1d5db;vertical-align:top}
.grid-2{display:flex;gap:15px}
.grid-2>div{flex:1}
.label{color:#6b7280;font-size:8pt;text-transform:uppercase;margin-bottom:1px}
.value{font-weight:600;font-size:10pt}
.footer{text-align:center;border-top:2px solid #e5e7eb;padding-top:10px;margin-top:20px;font-size:8pt;color:#9ca3af}
.visa-status{display:inline-block;padding:2px 8px;border-radius:3px;font-size:8pt;font-weight:600;text-transform:uppercase}
.visa-status-pending{background:#fef3c7;color:#92400e}
.visa-status-approved{background:#d1fae5;color:#065f46}
.visa-status-rejected{background:#fee2e2;color:#991b1b}
.visa-status-processing{background:#dbeafe;color:#1e40af}
.visa-status-delivered{background:#e0e7ff;color:#3730a3}
</style>
</head>
<body>

<div class="header">
    <h1>TravelBox</h1>
    <p style="font-size:11pt;font-weight:600">Visa Confirmation</p>
    <p>{{ $visa->country }} &bull; {{ $trip->trip_number }}</p>
</div>

<div style="text-align:center;margin-bottom:20px">
    <span class="visa-status visa-status-{{ $visa->status }}">{{ str_replace('_', ' ', ucfirst($visa->status ?? 'pending')) }}</span>
</div>

<div class="section">
    <div class="grid-2">
        <div>
            <div class="label">Country</div>
            <div class="value">{{ $visa->country ?? '—' }}</div>
        </div>
        <div>
            <div class="label">Visa Type</div>
            <div class="value">{{ str_replace('_', ' ', ucfirst($visa->visa_type ?? 'tourist')) }}</div>
        </div>
    </div>
</div>

<div class="section">
    <table>
        <tr>
            <td style="width:50%"><div class="label">Application Date</div><div class="value">{{ $visa->application_date?->format('M d, Y') ?: '—' }}</div></td>
            <td style="width:50%"><div class="label">Expected Delivery</div><div class="value">{{ $visa->expected_delivery?->format('M d, Y') ?: '—' }}</div></td>
        </tr>
        @if ($visa->approval_date)
        <tr>
            <td><div class="label">Approval Date</div><div class="value">{{ $visa->approval_date?->format('M d, Y') }}</div></td>
            <td><div class="label">Valid Until</div><div class="value">{{ $visa->valid_until?->format('M d, Y') ?: '—' }}</div></td>
        </tr>
        @endif
    </table>
</div>

@if ($visa->notes)
<div class="section">
    <h3>Notes</h3>
    <p style="font-size:9pt">{{ $visa->notes }}</p>
</div>
@endif

<div class="footer">
    <p>Generated by TravelBox ERP &bull; {{ now()->format('M d, Y H:i') }} &bull; travelbox.my</p>
    <p style="font-size:7pt">This is a computer-generated confirmation. Please ensure all visa documents are in order before travel.</p>
</div>

</body>
</html>
